import { api } from './client'
export const ext = {
  winProb: (raceId:string)=> api.get<any>(`/api/v1/live-win-prob/${raceId}`),
  winProbStream: (sessionKey:string, raceId:string)=> `/api/v1/live/${sessionKey}/win-prob-stream?race_id=${raceId}`,
  resim: (body:any)=> api.post<any>(`/api/v1/live/resim`, body),
  timeline: (raceId:string)=> api.get<any>(`/api/v1/timeline/${raceId}`),
  branch: (body:any)=> api.post<any>(`/api/v1/replay/branch-point`, body),
  counterfactual: (removeDnf=true)=> api.get<any>(`/api/v1/championship/counterfactual?remove_dnf=${removeDnf}`),
  transferOpts: ()=> api.get<any>(`/api/v1/transfer/options`),
  transfer: (body:any)=> api.post<any>(`/api/v1/transfer/simulate`, body),
  personas: ()=> api.get<any>(`/api/v1/personas`),
  personaChat: (team:string, body:any)=> api.post<any>(`/api/v1/personas/${team}/chat`, body),
  preview: (raceId:string)=> api.get<any>(`/api/v1/preview/${raceId}`),
  fingerprint: ()=> api.get<any>(`/api/v1/fingerprint`),
  meta: (raceId:string)=> api.get<any>(`/api/v1/meta/${raceId}`),
  crowdSubmit: (raceId:string, picks:string[])=> api.post<any>(`/api/v1/crowd/${raceId}/submit`, {picks}),
  crowd: (raceId:string)=> api.get<any>(`/api/v1/crowd/${raceId}`),
  lbSubmit: (body:any)=> api.post<any>(`/api/v1/leaderboard/submit`, body),
  leaderboard: (raceId:string)=> api.get<any>(`/api/v1/leaderboard?race_id=${raceId}`),
  market: (raceId:string)=> api.get<any>(`/api/v1/market/${raceId}`),
  marketTrade: (raceId:string, body:any)=> api.post<any>(`/api/v1/market/${raceId}/trade`, body),
  streak: ()=> api.get<any>(`/api/v1/streak`),
  sonify: (raceId:string)=> api.get<any>(`/api/v1/sonify/${raceId}`),
  rivalry: ()=> api.get<any>(`/api/v1/rivalry/graph`),
}
