"""initial schema

Revision ID: 032970242085
Revises: 
Create Date: 2026-09-10 18:47:31.288937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032970242085'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('response_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_table('circuits',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('laps', sa.Integer(), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=False),
    sa.Column('drs_zones', sa.Integer(), nullable=True),
    sa.Column('overtaking_rating', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('baseline', sa.Float(), nullable=False),
    sa.Column('backtest_season', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.String(length=50), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=True),
    sa.Column('total_probability_sum', sa.Float(), nullable=True),
    sa.Column('probability_validation_status', sa.String(length=20), nullable=True),
    sa.Column('validation_errors', sa.Text(), nullable=True),
    sa.Column('model_drift_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_metadata_race_id'), 'prediction_metadata', ['race_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.String(length=50), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=True),
    sa.Column('prediction_type', sa.String(length=50), nullable=True),
    sa.Column('driver_code', sa.String(length=10), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('confidence_interval', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_race_id'), 'predictions', ['race_id'], unique=False)
    op.create_table('session_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.String(length=50), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=True),
    sa.Column('strength_adjustments', sa.JSON(), nullable=True),
    sa.Column('grid_positions', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_data_race_id'), 'session_data', ['race_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('base', sa.String(length=100), nullable=True),
    sa.Column('engine', sa.String(length=50), nullable=True),
    sa.Column('championships', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_account_id', name='uq_user_provider_account')
    )
    op.create_table('constructor_standings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=50), nullable=False),
    sa.Column('wet_skill', sa.Integer(), nullable=True),
    sa.Column('reliability_base', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('picks_made', sa.Integer(), nullable=True),
    sa.Column('picks_resolved', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sprint', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_picks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.String(length=50), nullable=False),
    sa.Column('session', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('driver_id', sa.String(length=10), nullable=False),
    sa.Column('made_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'race_id', 'session', 'target', name='uq_pick_per_slot')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chaos_level', sa.Integer(), nullable=True),
    sa.Column('wet_influence', sa.Integer(), nullable=True),
    sa.Column('reliability_influence', sa.Integer(), nullable=True),
    sa.Column('strategy_aggressiveness', sa.Integer(), nullable=True),
    sa.Column('grid_weight', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('driver_standings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('podiums', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualifying_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('q1_time', sa.String(length=20), nullable=True),
    sa.Column('q2_time', sa.String(length=20), nullable=True),
    sa.Column('q3_time', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('grid', sa.Integer(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('fastest_lap', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race_results')
    op.drop_table('qualifying_results')
    op.drop_table('driver_standings')
    op.drop_table('user_settings')
    op.drop_table('user_picks')
    op.drop_table('races')
    op.drop_table('leaderboard')
    op.drop_table('drivers')
    op.drop_table('constructor_standings')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_index(op.f('ix_session_data_race_id'), table_name='session_data')
    op.drop_table('session_data')
    op.drop_index(op.f('ix_predictions_race_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_prediction_metadata_race_id'), table_name='prediction_metadata')
    op.drop_table('prediction_metadata')
    op.drop_table('model_runs')
    op.drop_table('circuits')
    op.drop_table('cache_entries')
    # ### end Alembic commands ###
